# Site Settings
title: "Digital Humanities Craft"
description: "Blogging about applied generative AI, LLM and Prompt Engineering for research support"
url: "https://dhcraft.org"
baseurl: "/excellence"

# Author
author:
  name: "Christopher Pollin"
  email: "christopher.pollin@dhcraft.org"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
# Only process blog markdown posts - everything else is static
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - promptotyping/          # Static web apps, no Jekyll needed
  - system_prompts/          # Documentation only, no Jekyll needed
  # NOTE: assets/ excluded on GitHub Pages but needed for local testing
  # Comment out the next line for local testing with `bundle exec jekyll serve`
  # - assets/                  # Served from parent site in production
  - README.md                # Repository documentation
  - CLAUDE.md                # AI assistant documentation
  - CITATION.cff             # Citation metadata

# Note: index.html is NOT excluded - Jekyll will copy it to _site/ without Liquid processing
# (no front matter = no processing, just copied as-is)

# SEO and Social
linkedin_username: christopher-pollin-463b0a204
mastodon:
  - username: chpollin
    instance: fedihum.org
github_username: chpollin

# Timezone
timezone: Europe/Vienna