# Site Settings
title: "Digital Humanities Craft"
description: "Blogging about applied generative AI, LLM and Prompt Engineering for research support"
url: "https://dhcraft.org"
baseurl: "/excellence"

# Author
author:
  name: "Christopher Pollin"
  email: "christopher.pollin@dhcraft.org"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/

# SEO and Social
linkedin_username: christopher-pollin-463b0a204
mastodon:
  - username: chpollin
    instance: fedihum.org
github_username: chpollin

# Timezone
timezone: Europe/Vienna